// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyMappersWeb.Data;

#nullable disable

namespace MonkeyMappersWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251218235540_ANewDataBase")]
    partial class ANewDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonkeyMappersWeb.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hobbitten",
                            SteamId = "STEAM_0:1:26854395"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Random User 1",
                            SteamId = "STEAM_0:1:26853395"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Random User 2",
                            SteamId = "STEAM_0:1:26854495"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
